"""Write DATA_CARD.md from the built benchmark so documented counts never drift from the files."""

from __future__ import annotations

import json
from pathlib import Path

import polars as pl

from slpbench.evaluate import BENCH, load_split

INTERIM = Path("data/interim")


def _md(df: pl.DataFrame) -> str:
    cols = df.columns
    out = ["| " + " | ".join(cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for r in df.iter_rows():
        out.append("| " + " | ".join(f"{v:,}" if isinstance(v, int) else ("" if v is None else str(v)) for v in r) + " |")
    return "\n".join(out)


def build_card() -> str:
    man = json.loads((BENCH / "manifest.json").read_text())
    rep = json.loads((INTERIM / "examples_report.json").read_text())
    ctx = pl.read_parquet(BENCH / "contexts.parquet")
    splits = {s: load_split(s) for s in ["train", "dev", "dev_semi", "test", "test_semi"]}
    allx = pl.concat([d.with_columns(pl.lit(s).alias("split")) for s, d in splits.items()], how="diagonal")

    meas = pl.concat([pl.read_parquet(p) for p in sorted((INTERIM / "measurements").glob("*.parquet"))])
    src = meas.group_by("species", "source").agg(
        pl.col("context").n_unique().alias("contexts"), pl.col("mechanism").first(),
        pl.len().alias("measured pairs"), (pl.col("label") == 1).sum().alias("SL"),
        (pl.col("label") == 0).sum().alias("non-SL"),
    ).sort("species", "source").with_columns(
        pl.col("source").is_in(list(man.get("excluded_sources", {}))).replace_strict({True: "excluded", False: "yes"}).alias("in benchmark"))

    per_split = allx.group_by("split", "species").agg(
        pl.len().alias("examples"), (pl.col("label") == 1).sum().alias("SL"),
        pl.col("context_id").n_unique().alias("contexts"),
    ).sort("split", "species")

    h = allx.filter(pl.col("species") == "human")
    anc = h.group_by("ancestry_group").agg(
        pl.col("context_id").n_unique().alias("cell lines"),
        (pl.col("split") == "test").sum().alias("test examples"),
        ((pl.col("split") == "test") & (pl.col("label") == 1)).sum().alias("test SL"),
        ((pl.col("split") == "dev") & (pl.col("label") == 1)).sum().alias("dev SL"),
    ).sort("ancestry_group")
    lines = h.group_by("context_id", "ancestry_group").agg(
        pl.len().alias("examples"), (pl.col("label") == 1).sum().alias("SL"),
        pl.col("sources").str.split(",").flatten().unique().sort().str.join(", ").alias("sources"),
    ).join(ctx.select("context_id", "cellosaurus_ac", "ancestry_basis", "disease"), on="context_id", how="left") \
        .sort("ancestry_group", "context_id")

    return f"""# {man["version"].upper().replace("SLB", "SLB-")} data card

Generated by `slpbench card` from `data/bench/{man['version']}` (built {man['built']}). Do not edit by hand.

## Sources

Per-source measured pairs after ID mapping, before cross-source merging. Labels follow the
per-source rules in [BENCHMARK.md](BENCHMARK.md#label-rules); unlabelled rows are the ambiguous band.
Sources marked excluded failed the reproducibility audit ([REPLICATION.md](REPLICATION.md)) and supply no labels.

{_md(src)}

Merging the same (species, context, pair) across sources: {rep['examples']:,} labelled examples;
{rep['conflicting_pairs_dropped']:,} pairs dropped because sources disagreed. Of
{rep['multi_source_positive_pairs']:,} pairs measured by 2+ sources in the same cell line where at least one
called SL, **{rep['multi_source_positive_agreement']:.0%}** were called SL by all of them (included sources only). That is how
reproducible an SL call from these screens is across studies, and it bounds how well any model can agree with them.

## Splits

Families (paralogs ≥ {man['paralog_min_identity']:.0%} identity + cross-species orthologs) are hashed to
test ({man['test_frac']:.0%}), dev ({man['dev_frac']:.0%}) or train. `test`/`dev` hold pairs with both genes in held-out
families; `*_semi` hold pairs with one held-out and one train gene. Pairs spanning dev and test are dropped.

{_md(per_split)}

## Human genetic ancestry

Ancestry is the donor's genotype-inferred super-population from Cellosaurus (Kessler et al. 2019):
the majority component (> 50%), otherwise `admixed`; `self_reported` marks lines with only a reported
population; `unknown` lines have neither and are not averaged into the human score.
European-ancestry lines dominate the public screens.

{_md(anc)}

### Cell lines

{_md(lines)}
"""


def main() -> None:
    Path("DATA_CARD.md").write_text(build_card())
    print("wrote DATA_CARD.md")
