"""Regenerate LEADERBOARD.md from results/<name>_test.json plus entries in leaderboard.yaml.

leaderboard.yaml:
    - name: lgbm
      result: results/lgbm_test.json
      description: gradient boosting on single-gene fitness, paralog identity, co-dependency
      trained_on: SLB-1.2 train
      leaky: false
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml

from slpbench.evaluate import BENCH, species_tiers



def render(entries: list[dict]) -> str:
    rows = []
    for e in entries:
        p = Path(e["result"])
        if not p.exists():
            continue
        r = json.loads(p.read_text())
        if r.get("benchmark") != BENCH.name:
            continue
        ci = r.get("slb_score_ci95")
        rows.append((e, r, ci))
    rows.sort(key=lambda t: (t[0].get("leaky", False), -t[1]["slb_score"]))
    main, aux = species_tiers()
    head = ("| # | model | SLB score (95% CI) | " + " | ".join(main) + " | " + " | ".join(f"*{a}*" for a in aux)
            + " | trained on | leaky |\n|" + "---|" * (5 + len(main) + len(aux)))
    lines = [head]
    rank = 0
    for e, r, ci in rows:
        rank_s = "–" if e.get("leaky") else str(rank := rank + 1)
        sc = {**r["species_scores"], **r.get("auxiliary_species_scores", {})}
        sp = " | ".join("n/a" if sc.get(s) is None or sc[s] != sc[s] else f"{sc[s]:.3f}" for s in main + aux)
        cis = f" ({ci[0]:.3f}–{ci[1]:.3f})" if ci else ""
        lines.append(f"| {rank_s} | **{e['name']}** — {e.get('description', '')} | {r['slb_score']:.3f}{cis} | "
                     f"{sp} | {e.get('trained_on', '')} | {'yes' if e.get('leaky') else 'no'} |")
    return (
        "# SLB leaderboard (test split)\n\n"
        "Generated by `slpbench leaderboard` from `leaderboard.yaml`. Species columns are the per-species\n"
        "components of the SLB score (fitness-balanced, context x screen stratified AUROC; human = mean over\n"
        "ancestry groups). Italic columns are auxiliary species: scored the same way, not in the SLB score;\n"
        "n/a = fewer than 20 test positives.\n"
        "Only results on the current benchmark version are shown.\n"
        "Leaky models were fitted on SL labels or screens involving held-out genes and are not ranked.\n\n"
        + "\n".join(lines) + "\n"
    )


def main(config: str = "leaderboard.yaml") -> None:
    entries = yaml.safe_load(Path(config).read_text())
    Path("LEADERBOARD.md").write_text(render(entries))
    print(Path("LEADERBOARD.md").read_text())
