"""Verify every leaderboard.yaml entry and write the table into README.md (and results/reports/leaderboard.md).

leaderboard.yaml:
    - name: lgbm
      result: results/slb/lgbm_test.json
      result_sha256: ...
      predictions: results/slb/lgbm_test.parquet
      description: gradient boosting on single-gene fitness, paralog identity, co-dependency
      trained_on: SLB train
      leaky: false
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import yaml

from slbench import evaluate as E

BENCH = E.BENCH
species_tiers = E.species_tiers


def _same_score(actual: float, reported: object, allow_na: bool = False) -> bool:
    if math.isnan(actual):
        return allow_na and (reported is None or (isinstance(reported, float) and math.isnan(reported)))
    if isinstance(reported, bool) or not isinstance(reported, (int, float)):
        return False
    return math.isfinite(actual) and math.isfinite(reported) and abs(actual - reported) <= 1e-10


def _verified_result(entry: dict) -> dict:
    result = Path(entry["result"])
    pred = Path(entry["predictions"])
    if E.file_sha256(result) != entry["result_sha256"]:
        raise ValueError(f"result JSON sha256 mismatch: {result}")
    r = json.loads(result.read_text())
    expected_manifest = E.file_sha256(BENCH / "manifest.json")
    if (r.get("benchmark") != E.bench_id(BENCH) or r.get("split") != "test"
            or r.get("manifest_sha256") != expected_manifest
            or r.get("scorer_version") != E.SCORER_VERSION
            or r.get("predictions_sha256") != E.file_sha256(pred)
            or r.get("missing_filled") != 0):
        raise ValueError(f"stale or unverified leaderboard result: {result}")
    ci = r.get("slb_score_ci95")
    if (not isinstance(ci, list) or len(ci) != 2
            or any(isinstance(x, bool) or not isinstance(x, (int, float)) or not math.isfinite(x) for x in ci)
            or not 0 <= ci[0] <= ci[1] <= 1):
        raise ValueError(f"invalid confidence interval in {result}")
    actual = E.evaluate(E.read_predictions(pred), "test")
    if not _same_score(actual["slb_score"], r.get("slb_score")) or actual["n"] != r.get("n"):
        raise ValueError(f"score in {result} does not match the submitted predictions")
    for field, allow_na in (("species_scores", False), ("auxiliary_species_scores", True)):
        reported = r.get(field)
        if not isinstance(reported, dict) or set(reported) != set(actual[field]):
            raise ValueError(f"{field} in {result} does not match the benchmark species")
        for sp, score in actual[field].items():
            if not _same_score(score, reported[sp], allow_na):
                raise ValueError(f"{field} in {result} does not match the submitted predictions: {sp}")
    return r



def render(entries: list[dict]) -> str:
    rows = []
    for e in entries:
        r = _verified_result(e)
        ci = r.get("slb_score_ci95")
        rows.append((e, r, ci))
    rows.sort(key=lambda t: (2 if t[0].get("leaky") else
                             1 if t[0].get("ranked") is False else 0,
                             -t[1]["slb_score"]))
    main, aux = species_tiers()
    head = ("| # | model | SLB score (95% CI) | " + " | ".join(main) + " | " + " | ".join(f"*{a}*" for a in aux)
            + " | trained on | leaky |\n|" + "---|" * (5 + len(main) + len(aux)))
    lines = [head]
    rank = 0
    for e, r, ci in rows:
        rank_s = "–" if e.get("leaky") or e.get("ranked") is False else str(rank := rank + 1)
        sc = {**r["species_scores"], **r.get("auxiliary_species_scores", {})}
        sp = " | ".join("n/a" if sc.get(s) is None or sc[s] != sc[s] else f"{sc[s]:.3f}" for s in main + aux)
        cis = f" ({ci[0]:.3f}–{ci[1]:.3f})" if ci else ""
        leak = e.get("leaky", False)
        leak_label = "possible" if leak == "possibly" else "yes" if leak else "no"
        lines.append(f"| {rank_s} | **{e['name']}** — {e.get('description', '')} | {r['slb_score']:.3f}{cis} | "
                     f"{sp} | {e.get('trained_on', '')} | {leak_label} |")
    return (
        "# SLB leaderboard (test split)\n\n"
        f"Generated by `slbench leaderboard` from `leaderboard.yaml` with scorer {E.SCORER_VERSION}.\n"
        "Result JSON is hash-pinned, and point/species scores are re-checked against prediction files.\n"
        "Species columns are the per-species components of the SLB score (fitness-balanced, context x\n"
        "screen stratified AUROC; human = mean over ancestry groups). Italic columns are auxiliary\n"
        "species: scored the same way, not in the SLB score;\n"
        "n/a = fewer than 20 test positives.\n"
        "Every listed result must match the current benchmark and scorer versions.\n"
        "Leaky models used SL labels or screens involving held-out genes; 'possible' means input provenance is unresolved. Both are unranked.\n"
        "Exploratory test ablations after an earlier test readout are also listed unranked.\n\n"
        + "\n".join(lines) + "\n"
    )


README = Path("README.md")
START, END = "<!-- leaderboard:start -->", "<!-- leaderboard:end -->"


def main(config: str = "leaderboard.yaml") -> None:
    text = render(yaml.safe_load(Path(config).read_text()))
    E.write_report("leaderboard.md", text)
    table = "\n".join(line for line in text.splitlines() if line.startswith("|"))
    head, rest = README.read_text().split(START, 1)
    README.write_text(f"{head}{START}\n{table}\n{END}{rest.split(END, 1)[1]}")
    print(text)
