"""Split-seed robustness: does the baseline ranking and headline hold when a different random
set of families is held out? Reads data/robustness/<salt>/res_<baseline>.json (built with
SLB_SALT/SLB_OUT by scripts/robustness.sh) plus the official build's results/<baseline>_test.json."""
import json
from pathlib import Path

import numpy as np

BASE = ["lgbm", "fitness_lgbm", "fitness", "paralog_identity", "codependency", "random"]
runs = {"official": {b: json.loads(Path(f"results/{b}_test.json").read_text()) for b in BASE}}
for d in sorted(Path("data/robustness").iterdir()):
    runs[d.name] = {b: json.loads((d / f"res_{b}.json").read_text()) for b in BASE}

lines = ["# Split-seed robustness (SLB-1.2)", "",
         "The official split and 4 alternative salts (different random families held out), same labels.",
         "Test-split SLB score per baseline. Generated by `scripts/robustness.sh` then `scripts/robustness.py`.", "",
         "| split | " + " | ".join(BASE) + " | ranking |", "|" + "---|" * (len(BASE) + 2)]
ranks = []
for name, r in runs.items():
    sc = [r[b]["slb_score"] for b in BASE]
    order = " > ".join(BASE[i] for i in np.argsort(sc)[::-1])
    ranks.append(order)
    lines.append(f"| {name} | " + " | ".join(f"{r[b]['slb_score']:.3f}" for b in BASE) + f" | {order} |")
sd = {b: np.std([runs[k][b]["slb_score"] for k in runs], ddof=1) for b in BASE}
lines += ["", "Across-split standard deviation of the SLB score: " + ", ".join(f"{b} {v:.3f}" for b, v in sd.items()) + ".",
          f"Identical ranking in {sum(r == ranks[0] for r in ranks)}/{len(ranks)} splits."]
sp = sorted({s for r in runs.values() for s in r["lgbm"]["species_scores"]})
for b in ("lgbm", "fitness_lgbm"):
    lines += ["", f"Per-species {b} score across splits:", "", "| split | " + " | ".join(sp) + " |", "|" + "---|" * (len(sp) + 1)]
    for name, r in runs.items():
        lines.append(f"| {name} | " + " | ".join(f"{r[b]['species_scores'].get(s, float('nan')):.3f}" for s in sp) + " |")
lines += ["", "Across-split standard deviation per species: " + "; ".join(
    f"{b} " + ", ".join(f"{s} {np.std([runs[k][b]['species_scores'][s] for k in runs], ddof=1):.3f}" for s in sp)
    for b in ("lgbm", "fitness_lgbm")) + "."]
Path("ROBUSTNESS.md").write_text("\n".join(lines) + "\n")
print("\n".join(lines))
