from pathlib import Path
import csv,hashlib,json,sys
import numpy as np,pandas as pd,torch

ROOT=Path(__file__).resolve().parents[2]; OUT=ROOT/"results/sl_predict"; sys.path.insert(0,str(Path(__file__).parent))
from world_model import encode_genes,load_residual_endpoint

def build():
    rows=list(csv.DictReader(open(ROOT/"data/feng2024/data/preprocessed_data/meta_table_9845.csv"))); symbols=np.asarray([r["symbol"].upper() for r in rows]); ens={r["ensembl_gene_id"].split(".")[0]:r["symbol"].upper() for r in rows if r["ensembl_gene_id"]}; ids={x:i for i,x in enumerate(symbols)}; basal=np.load(OUT/"basal_context.npz"); path=ROOT/"data/depmap24q2/OmicsExpressionProteinCodingGenesTPMLogp1.csv"; header=pd.read_csv(path,nrows=0).columns; named={x.rsplit(" (",1)[0].upper():x for x in header[1:]}; use=[header[0]]+[named[x] for x in symbols if x in named]; frame=pd.read_csv(path,usecols=use,dtype={header[0]:str}); fr={x:i for i,x in enumerate(frame.iloc[:,0].astype(str))}; x=np.full((len(basal["model_ids"]),len(symbols)),np.nan,"float32")
    ordered=frame.iloc[[fr[m] for m in basal["model_ids"].astype(str)]]
    for col in use[1:]:x[:,ids[col.rsplit(" (",1)[0].upper()]]=ordered[col].to_numpy("float32")
    fit=basal["train_cell"]; mean=np.nanmean(x[fit],0); scale=np.nanstd(x[fit],0); good=np.isfinite(mean)&(scale>1e-4); held=set(json.loads((OUT/"slkb_outcomes_intervention_external.json").read_text())["symbols"]); safe=good&~np.isin(symbols,tuple(held)); z=np.zeros_like(x); np.divide(x-mean,scale,out=z,where=good); z=np.nan_to_num(z).clip(-5,5); projection=np.random.default_rng(731).choice((-1.,1.),(safe.sum(),128)).astype("float32")/np.sqrt(safe.sum()); state=z[:,safe]@projection; center=state[fit].mean(0); state_scale=state[fit].std(0).clip(.1); state=(state-center)/state_scale; error=float(np.abs(state-basal["cell_state"]).max()); np.savez_compressed(OUT/"context_projection.npz",symbols=symbols,expression_mean=mean,expression_scale=scale,safe=safe,projection=projection,center=center,state_scale=state_scale)
    source_root=ROOT/"data/perturbseq_sources/base"; source_names=basal["sources"].astype(str)[:5]; records=[]; audits=[]; val=lambda s:int.from_bytes(hashlib.sha256(s.encode()).digest()[:4],"big")%5==0; safe_ids=np.flatnonzero(safe); safe_row={g:i for i,g in enumerate(safe_ids)}
    for sid,name in enumerate(source_names):
        raw=np.load(source_root/f"{name}.npz"); names=np.asarray([ens.get(str(v).split(".")[0],str(v).upper()) for v in raw["feature_name"]]); fmap={v:i for i,v in enumerate(names)}; common=np.asarray([g for g in safe_ids if symbols[g] in fmap]); cols=np.asarray([fmap[symbols[g]] for g in common]); delta=raw["future_state"][:,cols]-raw["control_mean"][cols]; target=(delta/scale[common])@projection[[safe_row[g] for g in common]]/state_scale; a=np.char.upper(raw["endpoint_a"].astype(str)); card=raw["cardinality"]; keep=(card==1)&np.asarray([g in ids and g not in held for g in a]); role=np.asarray([1 if val(g) else 0 for g in a[keep]],"int8"); records.append((np.asarray([ids[g] for g in a[keep]],"int16"),np.full(keep.sum(),sid,"int8"),role,target[keep].astype("float32"))); audits.append({"source":name,"overlap_safe_genes":len(common),"single_rows":int(keep.sum()),"train_rows":int((role==0).sum()),"validation_rows":int((role==1).sum())})
    arrays={"gene":np.concatenate([r[0] for r in records]),"source":np.concatenate([r[1] for r in records]),"role":np.concatenate([r[2] for r in records]),"target":np.concatenate([r[3] for r in records]),"context_state":basal["source_state"][:5],"sources":source_names}; np.savez_compressed(OUT/"context_transition.npz",**arrays); audit={"schema":"sl-predict-context-transition-v1","reference_models":len(x),"safe_genes":int(safe.sum()),"projection_max_abs_error":error,"projection_verified":bool(error<=1e-5),"sources":audits,"rows":len(arrays["gene"]),"train_rows":int((arrays["role"]==0).sum()),"validation_rows":int((arrays["role"]==1).sum()),"double_perturbation_data_used":False,"sl_labels_used":False}; (OUT/"context_transition.json").write_text(json.dumps(audit,indent=2)); print(json.dumps(audit,indent=2)); return audit

def build_extended():
    base=np.load(OUT/"context_transition.npz"); proj=np.load(OUT/"context_projection.npz"); basal=np.load(OUT/"basal_context.npz"); symbols=proj["symbols"].astype(str); ids={x:i for i,x in enumerate(symbols)}; safe_ids=np.flatnonzero(proj["safe"]); safe_row={g:i for i,g in enumerate(safe_ids)}; held=set(json.loads((OUT/"slkb_outcomes_intervention_external.json").read_text())["symbols"]); val=lambda s:int.from_bytes(hashlib.sha256(s.encode()).digest()[:4],"big")%5==0; records=[(base["gene"],base["source"],base["role"],base["target"])]; contexts=list(base["context_state"]); names=list(base["sources"].astype(str)); audits=[]
    for filename,context_sid in (("wessels2023.npz",5),("joung2023.npz",6)):
        raw=np.load(ROOT/"data/perturbseq_sources"/filename); fmap={str(v).upper():i for i,v in enumerate(raw["feature_name"])}; common=np.asarray([g for g in safe_ids if symbols[g] in fmap]); cols=np.asarray([fmap[symbols[g]] for g in common]); a=np.char.upper(raw["endpoint_a"].astype(str)); keep=(raw["cardinality"]==1)&np.asarray([g in ids and g not in held and not val(g) for g in a]); delta=raw["future_state"][:,cols]-raw["control_mean"][cols]; target=(delta/proj["expression_scale"][common])@proj["projection"][[safe_row[g] for g in common]]/proj["state_scale"]; sid=len(names); name=filename[:-4]; records.append((np.asarray([ids[g] for g in a[keep]],"int16"),np.full(keep.sum(),sid,"int8"),np.zeros(keep.sum(),"int8"),target[keep].astype("float32"))); contexts.append(basal["source_state"][context_sid]); names.append(name); audits.append({"source":name,"overlap_safe_genes":len(common),"training_rows":int(keep.sum()),"validation_rows":0})
    moi=np.load(OUT/"gse337988_moi_state.npz",allow_pickle=True); frame=pd.read_csv(ROOT/"data/perturbseq_sources/gse337988_audit/GSE337988_sublib2_de_matrices_lfc_matrix_Med.csv.gz",dtype={"gene":"string"}).set_index("gene"); fmap={str(v).upper():i for i,v in enumerate(frame.index)}; common=np.asarray([g for g in safe_ids if symbols[g] in fmap]); rows=np.asarray([fmap[symbols[g]] for g in common]); keep=moi["role"]==0; conditions=moi["condition"][keep].astype(str); delta=frame.iloc[rows][conditions].to_numpy("float32").T; target=(delta/proj["expression_scale"][common])@proj["projection"][[safe_row[g] for g in common]]/proj["state_scale"]; sid=len(names); records.append((moi["gene"][keep].astype("int16"),np.full(keep.sum(),sid,"int8"),np.zeros(keep.sum(),"int8"),target.astype("float32"))); model=np.flatnonzero(basal["model_ids"].astype(str)=="ACH-001061"); assert len(model)==1; contexts.append(basal["cell_state"][model[0]]); names.append("gse337988_med"); audits.append({"source":"gse337988_med","overlap_safe_genes":len(common),"training_rows":int(keep.sum()),"discarded_held_rows":int((~keep).sum()),"validation_rows":0})
    arrays={"gene":np.concatenate([r[0] for r in records]),"source":np.concatenate([r[1] for r in records]),"role":np.concatenate([r[2] for r in records]),"target":np.concatenate([r[3] for r in records]),"context_state":np.asarray(contexts,"float32"),"sources":np.asarray(names)}; np.savez_compressed(OUT/"context_transition_extended.npz",**arrays); audit={"schema":"sl-predict-extended-context-transition-v1","rows":len(arrays["gene"]),"train_rows":int((arrays["role"]==0).sum()),"validation_rows":int((arrays["role"]==1).sum()),"original_validation_rows_unchanged":int((base["role"]==1).sum()),"supplementary_sources":audits,"double_perturbation_data_used":False,"sl_labels_used":False}; (OUT/"context_transition_extended.json").write_text(json.dumps(audit,indent=2)); print(json.dumps(audit,indent=2)); return audit

class Shift(torch.nn.Module):
    def __init__(self):super().__init__(); self.net=torch.nn.Sequential(torch.nn.LayerNorm(256),torch.nn.Linear(256,256),torch.nn.GELU(),torch.nn.Linear(256,128))
    def forward(self,g,c):return self.net(torch.cat((g,c),1))

def fit(epochs=50):
    torch.manual_seed(731); np.random.seed(731); device="cuda" if torch.cuda.is_available() else "cpu"; data=np.load(OUT/"context_transition.npz"); state=np.load(OUT/"features_spectral_safe.npz")["state"].astype("float32"); model_dir=OUT/"native_spectral_safe_intervention_basal_perturbseq_residual64_p12_d3_t10_r3"; endpoint=load_residual_endpoint(model_dir/"world_model.pt",state.shape[1],device); genes=torch.as_tensor(encode_genes(endpoint.world,state,device),device=device); target=torch.as_tensor(data["target"],device=device); gene=torch.as_tensor(data["gene"].astype("int64"),device=device); source=torch.as_tensor(data["source"].astype("int64"),device=device); context=torch.as_tensor(data["context_state"],device=device); train=np.flatnonzero(data["role"]==0); valid=np.flatnonzero(data["role"]==1); head=Shift().to(device); opt=torch.optim.AdamW(head.parameters(),3e-4,weight_decay=1e-3); history=[]; saved=[]
    @torch.no_grad()
    def evaluate(epoch):
        pred=head(genes[gene[valid]],context[source[valid]]); rows=[]
        for sid,name in enumerate(data["sources"].astype(str)):
            at=torch.as_tensor(np.flatnonzero(data["source"][valid]==sid),device=device); p=pred[at]; y=target[torch.as_tensor(valid,device=device)[at]]; huber=float(torch.nn.functional.huber_loss(p,y)); zero=float(torch.nn.functional.huber_loss(torch.zeros_like(y),y)); cosine=float(torch.nn.functional.cosine_similarity(p,y).mean()); rows.append({"source":name,"rows":len(at),"zero_huber":zero,"huber":huber,"improvement":1-huber/zero,"cosine":cosine})
        row={"epoch":epoch,"source_macro_huber":float(np.mean([x["huber"] for x in rows])),"source_macro_zero":float(np.mean([x["zero_huber"] for x in rows])),"source_macro_cosine":float(np.mean([x["cosine"] for x in rows])),"sources":rows}; row["improvement"]=1-row["source_macro_huber"]/row["source_macro_zero"]; history.append(row); saved.append({k:v.detach().cpu().clone() for k,v in head.state_dict().items()}); return row
    print(json.dumps(evaluate(0)),flush=True)
    for epoch in range(epochs):
        order=np.random.default_rng(731+epoch).permutation(train); head.train()
        for at in range(0,len(order),512):
            ix=torch.as_tensor(order[at:at+512],device=device); loss=torch.nn.functional.huber_loss(head(genes[gene[ix]],context[source[ix]]),target[ix]); opt.zero_grad(); loss.backward(); opt.step()
        head.eval(); row=evaluate(epoch+1); print(json.dumps({k:v for k,v in row.items() if k!="sources"}),flush=True)
    best=min(range(len(history)),key=lambda i:history[i]["source_macro_huber"]); selected=history[best]; head.load_state_dict(saved[best]); required=[x for x in selected["sources"] if x["rows"]>=10]; advanced=selected["improvement"]>=.05 and selected["source_macro_cosine"]>0 and all(x["cosine"]>0 for x in required); torch.save(head.state_dict(),model_dir/"context_transition_head.pt"); result={"schema":"sl-predict-context-transition-head-v1","parameters":sum(p.numel() for p in head.parameters()),"selected":selected,"advanced":bool(advanced),"double_perturbation_data_used":False,"sl_labels_used":False,"history":history}; (model_dir/"context_transition_metrics.json").write_text(json.dumps(result,indent=2)); print(json.dumps({k:v for k,v in result.items() if k!="history"},indent=2)); return result

def fit_direction(epochs=80,pack="context_transition.npz",artifact="unit_context_transition"):
    torch.manual_seed(733); np.random.seed(733); device="cuda" if torch.cuda.is_available() else "cpu"; data=np.load(OUT/pack); state=np.load(OUT/"features_spectral_safe.npz")["state"].astype("float32"); model_dir=OUT/"native_spectral_safe_intervention_basal_perturbseq_residual64_p12_d3_t10_r3"; endpoint=load_residual_endpoint(model_dir/"world_model.pt",state.shape[1],device); genes=torch.as_tensor(encode_genes(endpoint.world,state,device),device=device); target=torch.nn.functional.normalize(torch.as_tensor(data["target"],device=device),dim=1); gene=torch.as_tensor(data["gene"].astype("int64"),device=device); source=torch.as_tensor(data["source"].astype("int64"),device=device); context=torch.as_tensor(data["context_state"],device=device); train=np.flatnonzero(data["role"]==0); valid=np.flatnonzero(data["role"]==1); counts=np.bincount(data["source"][train],minlength=len(data["sources"])); head=Shift().to(device); opt=torch.optim.AdamW(head.parameters(),3e-4,weight_decay=1e-3); history=[]; saved=[]
    @torch.no_grad()
    def evaluate(epoch):
        pred=torch.nn.functional.normalize(head(genes[gene[valid]],context[source[valid]]),dim=1); rows=[]
        for sid,name in enumerate(data["sources"].astype(str)):
            at=torch.as_tensor(np.flatnonzero(data["source"][valid]==sid),device=device)
            if len(at): cosine=float(torch.nn.functional.cosine_similarity(pred[at],target[torch.as_tensor(valid,device=device)[at]]).mean()); rows.append({"source":name,"rows":len(at),"cosine":cosine})
        row={"epoch":epoch,"source_macro_cosine":float(np.mean([x["cosine"] for x in rows])),"sources":rows}; history.append(row); saved.append({k:v.detach().cpu().clone() for k,v in head.state_dict().items()}); return row
    print(json.dumps(evaluate(0)),flush=True)
    for epoch in range(epochs):
        order=np.random.default_rng(733+epoch).permutation(train); head.train()
        for at in range(0,len(order),512):
            ix=torch.as_tensor(order[at:at+512],device=device); pred=torch.nn.functional.normalize(head(genes[gene[ix]],context[source[ix]]),dim=1); raw=1-torch.nn.functional.cosine_similarity(pred,target[ix]); weight=torch.as_tensor(1/counts[data["source"][order[at:at+512]]],dtype=torch.float32,device=device); loss=(raw*weight).sum()/weight.sum(); opt.zero_grad(); loss.backward(); opt.step()
        head.eval(); row=evaluate(epoch+1); print(json.dumps({k:v for k,v in row.items() if k!="sources"}),flush=True)
    best=max(range(len(history)),key=lambda i:history[i]["source_macro_cosine"]); selected=history[best]; head.load_state_dict(saved[best]); required=[x for x in selected["sources"] if x["rows"]>=10]; advanced=selected["source_macro_cosine"]>=.20 and all(x["cosine"]>=.10 for x in required); torch.save(head.state_dict(),model_dir/f"{artifact}_head.pt"); result={"schema":f"sl-predict-{artifact.replace('_','-')}-v1","parameters":sum(p.numel() for p in head.parameters()),"selected":selected,"advanced":bool(advanced),"double_perturbation_data_used":False,"sl_labels_used":False,"history":history}; (model_dir/f"{artifact}_metrics.json").write_text(json.dumps(result,indent=2)); print(json.dumps({k:v for k,v in result.items() if k!="history"},indent=2)); return result

if __name__=="__main__":{"build":build,"build_extended":build_extended,"fit":fit,"direction":fit_direction,"direction_extended":lambda:fit_direction(pack="context_transition_extended.npz",artifact="extended_unit_context_transition")}.get(sys.argv[1] if len(sys.argv)>1 else "build")()
